language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
  - '7'
  - '6'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
after_success:
  - npm run release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
